logging:
  level:
    ROOT: INFO
    org.springframework: OFF
    org.hibernate: ERROR
    com.kg.springboot1: ALL
   
  pattern:
    console: "- %msg%n"
    file: "*[%-5p]-- %m--%n"
  file: logs/docketLogGen2.log